# Generated by Django 5.2.3 on 2025-06-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('qr_data', models.CharField(max_length=255)),
                ('access_granted', models.BooleanField()),
                ('event_type', models.CharField(default='acceso_general', max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
