# Generated by Django 5.2.3 on 2025-06-16 04:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0002_accesspoint_person_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='¿Está este permiso actualmente activo?')),
                ('valid_from', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Fecha y hora desde la cual el permiso es válido (opcional)', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text="Fecha y hora hasta la cual el permiso es válido (opcional, dejar en blanco para 'sin caducidad')", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_point', models.ForeignKey(help_text='Punto de acceso para el cual se concede el permiso', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='log_viewer_app.accesspoint')),
                ('person', models.ForeignKey(help_text='Persona a la que se concede el permiso', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='log_viewer_app.person')),
            ],
            options={
                'unique_together': {('person', 'access_point')},
            },
        ),
    ]
