# Generated by Django 5.2.3 on 2025-06-16 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0003_accesspermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre descriptivo para el dispositivo (e.g., 'Controlador Puerta Garaje Izquierda')", max_length=150)),
                ('device_id', models.CharField(help_text='Identificador único del dispositivo (e.g., MAC address, ID de serie del dt-r002)', max_length=100, unique=True)),
                ('mqtt_topic', models.CharField(help_text="Tópico MQTT para enviar comandos a este dispositivo (e.g., 'parking/gate1/control')", max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del dispositivo (opcional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='¿Está este dispositivo actualmente activo y operativo?')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el dispositivo o su configuración')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_point', models.ForeignKey(blank=True, help_text='Punto de acceso que este dispositivo controla', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_devices', to='log_viewer_app.accesspoint')),
            ],
        ),
    ]
