# Generated by Django 5.2.3 on 2025-06-16 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0004_controldevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se registró el pago')),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria'), ('paypal', 'PayPal'), ('otro', 'Otro')], default='efectivo', help_text='Método de pago utilizado', max_length=50)),
                ('reference_number', models.CharField(blank=True, help_text='Número de referencia o ID de transacción (opcional)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el pago (opcional)', null=True)),
                ('processed_for_access', models.BooleanField(default=False, help_text='Indica si este pago ya ha sido procesado para activar/extender un acceso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(help_text='Persona que realizó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='log_viewer_app.person')),
            ],
        ),
    ]
