# Generated by Django 5.2.3 on 2025-06-16 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0005_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario del sistema Django asociado a esta persona (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controldevice',
            name='device_id',
            field=models.CharField(help_text='Identificador único del dispositivo', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='controldevice',
            name='mqtt_topic',
            field=models.CharField(help_text='Tópico MQTT para enviar comandos', max_length=255),
        ),
        migrations.AlterField(
            model_name='controldevice',
            name='name',
            field=models.CharField(help_text='Nombre descriptivo para el dispositivo', max_length=150),
        ),
        migrations.AlterField(
            model_name='controldevice',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionales'),
        ),
    ]
