# Generated by Django 5.2.3 on 2025-06-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0006_person_user_alter_controldevice_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre del servicio o producto (e.g., 'Estacionamiento Mensual', 'Tarjeta de Acceso')", max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del servicio', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio base del servicio', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
