# Generated by Django 5.2.3 on 2025-06-16 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0007_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Fecha de inicio de la suscripción')),
                ('end_date', models.DateField(blank=True, help_text='Fecha de fin de la suscripción (opcional, dejar en blanco si es indefinida o gestionada por renovaciones)', null=True)),
                ('billing_cycle', models.CharField(choices=[('once', 'Pago Único'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('annually', 'Anual'), ('other', 'Otro')], default='monthly', help_text='Ciclo de facturación para esta suscripción', max_length=20)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Precio especial para esta suscripción (si difiere del precio base del servicio)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta suscripción está actualmente activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(help_text='Persona asociada a esta suscripción', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='log_viewer_app.person')),
                ('service', models.ForeignKey(help_text='Servicio al que está suscrita la persona', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='log_viewer_app.service')),
            ],
            options={
                'ordering': ['-start_date', 'person__full_name'],
            },
        ),
    ]
