# Generated by Django 5.2.3 on 2025-06-16 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0008_usersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Número de factura único (podría generarse automáticamente)', max_length=50, unique=True)),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Monto total a pagar en esta factura', max_digits=10)),
                ('due_date', models.DateField(help_text='Fecha de vencimiento para el pago de esta factura')),
                ('paid_date', models.DateField(blank=True, help_text='Fecha en que se completó el pago de esta factura (opcional)', null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('paid', 'Pagada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada'), ('partial', 'Parcialmente Pagada')], default='pending', help_text='Estado actual de la factura', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas o comentarios adicionales sobre la factura (opcional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(help_text='Persona a la que se emite la factura', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='log_viewer_app.person')),
                ('user_subscription', models.ForeignKey(blank=True, help_text='Suscripción asociada a esta factura (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='log_viewer_app.usersubscription')),
            ],
            options={
                'ordering': ['-due_date', 'person__full_name'],
            },
        ),
    ]
