# Generated by Django 5.2.3 on 2025-06-16 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0009_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Factura a la que se aplica este pago (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='log_viewer_app.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, help_text='Monto total a pagar', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(help_text='Fecha de vencimiento para el pago'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(help_text='Número de factura único', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas o comentarios adicionales (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, help_text='Fecha en que se completó el pago (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('once', 'Pago Único'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('annually', 'Anual'), ('other', 'Otro')], default='monthly', help_text='Ciclo de facturación', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateField(blank=True, help_text='Fecha de fin de la suscripción (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio especial para esta suscripción', max_digits=10, null=True),
        ),
    ]
