# Generated by Django 5.2.3 on 2025-06-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0010_payment_invoice_alter_invoice_amount_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_temporary_guest',
            field=models.BooleanField(default=False, help_text='Indica si esta persona es un invitado temporal'),
        ),
        migrations.AddField(
            model_name='person',
            name='registered_by',
            field=models.ForeignKey(blank=True, help_text='Usuario o persona anfitriona que registró a este invitado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_guests', to='log_viewer_app.person'),
        ),
    ]
