# Generated by Django 5.2.3 on 2025-06-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0011_person_is_temporary_guest_person_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='billing_cycle_anchor_day',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Día del mes para el anclaje de facturación (e.g., 1, 15, 28). Usado para determinar cuándo generar la factura en ciclos periódicos.', null=True),
        ),
    ]
