# Generated by Django 5.2.3 on 2025-06-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0012_usersubscription_billing_cycle_anchor_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cycle_start_date',
            field=models.DateField(blank=True, help_text='Fecha de inicio del ciclo de facturación que cubre esta factura', null=True),
        ),
    ]
