# Generated by Django 5.2.3 on 2025-06-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0013_invoice_cycle_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la empresa o inquilino', max_length=150, unique=True)),
                ('subdomain_prefix', models.CharField(blank=True, help_text='Prefijo de subdominio o identificador en URL (opcional, solo caracteres válidos para URL/DNS)', max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
