# Generated by Django A.B on YYYY-MM-DD HH:MM (Django will put the actual timestamp here)
from django.db import migrations

# Nombres de los modelos que necesitan ser actualizados
MODEL_NAMES_TO_UPDATE = [
    'Person', 'Vehicle', 'AccessPoint', 'ControlDevice',
    'AccessPermission', 'Service', 'UserSubscription',
    'Invoice', 'Payment', 'AccessLog'
]
DEFAULT_TENANT_NAME = "Empresa Principal (Default)"
DEFAULT_TENANT_SUBDOMAIN = "default" # Opcional

def populate_tenant_forward(apps, schema_editor):
    Tenant = apps.get_model('log_viewer_app', 'Tenant')
    db_alias = schema_editor.connection.alias

    # Crear o obtener el Tenant por defecto
    default_tenant, created = Tenant.objects.using(db_alias).get_or_create(
        name=DEFAULT_TENANT_NAME,
        defaults={'subdomain_prefix': DEFAULT_TENANT_SUBDOMAIN}
    )
    if created:
        print(f"Tenant por defecto '{DEFAULT_TENANT_NAME}' creado.")
    else:
        print(f"Tenant por defecto '{DEFAULT_TENANT_NAME}' ya existía.")

    for model_name in MODEL_NAMES_TO_UPDATE:
        Model = apps.get_model('log_viewer_app', model_name)
        # Actualizar solo los registros que tengan tenant_id NULL
        # Usamos .all() si el campo acaba de ser añadido y no tiene default,
        # o .filter(tenant__isnull=True) si el campo ya existía con null=True.
        # Dado que la migración anterior añadió el campo como null=True, filtramos por null.
        updated_count = Model.objects.using(db_alias).filter(tenant__isnull=True).update(tenant=default_tenant)
        if updated_count > 0:
            print(f"Actualizados {updated_count} registros en el modelo {model_name} con el tenant por defecto.")
        else:
            print(f"No se necesitaron actualizaciones para el modelo {model_name} (o no hay registros con tenant nulo).")

def populate_tenant_backward(apps, schema_editor):
    # Opcional: Si se quisiera revertir, se podrían poner los tenant_id a NULL.
    # Por simplicidad, y porque el siguiente paso es hacerlos NOT NULL,
    # un 'pass' es aceptable aquí. Si se quisiera revertir completamente,
    # se debería tener cuidado de no borrar el Tenant por defecto si otros datos dependen de él.
    print("Operación hacia atrás para populate_default_tenant no realiza cambios (los campos tenant_id permanecen).")
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0015_add_tenant_foreign_keys'), # Depende de la migración anterior
    ]

    operations = [
        migrations.RunPython(populate_tenant_forward, populate_tenant_backward),
    ]
