# Generated by Django 5.2.3 on 2025-06-17 03:12

import django.db.models.deletion
import log_viewer_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0016_populate_default_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='tenant',
            field=models.ForeignKey(default=log_viewer_app.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='log_viewer_app.tenant'),
        ),
        migrations.AlterField(
            model_name='accesspermission',
            name='tenant',
            field=models.ForeignKey(default=log_viewer_app.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='log_viewer_app.tenant'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='tenant',
            field=models.ForeignKey(default=log_viewer_app.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='access_points', to='log_viewer_app.tenant'),
        ),
        migrations.AlterField(
            model_name='controldevice',
            name='tenant',
            field=models.ForeignKey(default=log_viewer_app.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='control_devices', to='log_viewer_app.tenant'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(default=log_viewer_app.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='log_viewer_app.tenant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(default=log_viewer_app.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='log_viewer_app.tenant'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tenant',
            field=models.ForeignKey(default=log_viewer_app.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='log_viewer_app.tenant'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(default=log_viewer_app.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='log_viewer_app.tenant'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='tenant',
            field=models.ForeignKey(default=log_viewer_app.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='log_viewer_app.tenant'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tenant',
            field=models.ForeignKey(default=log_viewer_app.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='log_viewer_app.tenant'),
        ),
    ]
