# Generated by Django 5.2.3 on 2025-06-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0019_alter_accesslog_tenant_alter_accesspermission_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='identifier',
            field=models.CharField(help_text='Identificador único (e.g., DNI, ID de empleado)', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(help_text='Placa o matrícula del vehículo', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('tenant', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('tenant', 'license_plate')},
        ),
    ]
