# Generated by Django 5.2.3 on 2025-06-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer_app', '0020_update_uniqueness_person_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesspoint',
            options={'ordering': ['tenant', 'name']},
        ),
        migrations.AlterModelOptions(
            name='controldevice',
            options={'ordering': ['tenant', 'name']},
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='name',
            field=models.CharField(help_text="Nombre o ID único del punto de acceso (e.g., 'Puerta Principal Garaje', 'Torno Entrada Este')", max_length=100),
        ),
        migrations.AlterField(
            model_name='controldevice',
            name='device_id',
            field=models.CharField(help_text='Identificador único del dispositivo', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='accesspoint',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='controldevice',
            unique_together={('tenant', 'device_id')},
        ),
    ]
